destination: _site
permalink: /blog/:year/:month/:day/:title
tag_dir: /blog/tag
markdown: rdiscount
pygments: true

nav_links:
    -
        url: "/software-design.html"
        label: "Software Design"
    -
        url: "/software-testability.html"
        label: "Testability"
    -
        url: "/programming-languages.html"
        label: "Programming Languages"
