destination: _site
permalink: /:year/:month/:day/:title
markdown: rdiscount
pygments: true

nav_links:
    -
        url: "/software-testability.html"
        label: "Software Testability"
    -
        url: "/software-design.html"
        label: "Software Design"
