destination: _site
permalink: /blog/:year/:month/:day/:title
tag_dir: /blog/tag
markdown: rdiscount
pygments: true
exclude:
    -   README.md

nav_links:
    -
        url: "/software-design"
        label: "Software Design"
    -
        url: "/testability"
        label: "Testability"
    -
        url: "/programming-languages"
        label: "Programming Languages"
