destination: _site
permalink: /:year/:month/:day/:title
markdown: rdiscount
pygments: true

nav_links:
    -
        url: "/religion.html"
        label: "Religion"
    -
        url: "/software.html"
        label: "Software"
    -
        url: "/about.html"
        label: "About Me"